language: java
install: mvn install -DskipTests -Dgpg.skip
addons:
  apt:
    packages:
      - openjdk-6-jdk

jdk:
  - openjdk6
  - oraclejdk8
  - oraclejdk9
  - openjdk10
  - openjdk11
  - oraclejdk11
